### ISSUE TITLE
[BUG] Update top trending job is failing

### ISSUE THREAD

**Issue by icyflame** [metakgp/metakgp-wiki#74]
The failure is because of the lack of the python module `oauth2client`: https://github.com/googleapis/oauth2client

It looks like this module has been deprecated recently. The usage of `google-auth` is recommended on the repository page. This is the particular module inside `google-auth` that we would be using: https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#module-google.oauth2.service_account

### Failure log

```sh
icyflame@metakgp-blr:~$ docker exec metakgp-wiki_jobs_1 /root/update_top_trending.sh
Updating Top and Trending Pages
+ echo 'Updating Top and Trending Pages'
+ cd /root/pywikibot
+ export METAKGP_BOT_NAME=batman
+ METAKGP_BOT_NAME=batman
+ timeout 10s python pwb.py login
Logging in to metakgp:en as Batman@update-statistics
Logged in on metakgp:en as Batman.
+ timeout 30s python pwb.py updatestatistics
Traceback (most recent call last):
  File "pwb.py", line 264, in <module>
    if not main():
  File "pwb.py", line 257, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "pwb.py", line 120, in run_python_file
    main_mod.__dict__)
  File "./scripts/updatestatistics.py", line 7, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ImportError: No module named oauth2client.service_account
CRITICAL: Closing network session.
<type 'exceptions.ImportError'>
```

**Comment by harshkhandeparkar** [comment]
Irrelevant due to #111
